  spring:
    data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: db_ms-cars
      port: 27017
      host: localhost
      driver: com.mongodb.MongoClient
    profiles:
        active: dev